{
  "language": "node_js",
  "node_js": "8",
  "script": [
    "npm run lint",
    "npm run build",
    "npm run test",
  ],
  "install": [
    "npm ci",
    "npm install codecov -g",
    "npm i typescript",
  ],
  "after_success": [ "codecov" ]
}